### ISSUE TITLE
user1 needs admin role in the openshift-cicd namespace

### ISSUE THREAD

**Issue by satyaj** [gpe-mw-training/rhte2019_E2E_API_Lifecycle_Mgmt_labs#10]
The user user1 needs to have cluster admin, or admin privileges to all the namespaces created so that it has ability to start pipeline builds from the openshift-cicd namespace.

**Comment by jbride** [comment]
user1 now has admin role to openshift-cicd project

**Comment by satyaj** [comment]
Verified and closed
