### ISSUE TITLE
Two Jenkins deployed to openbanking-cicd namespace

### ISSUE THREAD

**Issue by satyaj** [gpe-mw-training/rhte2019_E2E_API_Lifecycle_Mgmt_labs#11]
The openbanking-cicd namespace has 2 Jenkins installed

![Selection_192](https://user-images.githubusercontent.com/5753166/62559559-d8011480-b898-11e9-997e-2add0e373530.png)

Only the openbanking-jenkins is needed. The 2nd Jenkins should not be installed as part of ansible script.

**Comment by jbride** [comment]
@satyaj  :   I'm not seeing an additional DC called _jenkins_ in _openbanking-cicd_ namespace

**Comment by satyaj** [comment]
The second jenkins is deployed when a pipeline build is started. it is a jenkins ephemeral deployment. Need to investigate why it deploys this when a Jenkins is already available and being used for the jenkins jobs in this namespace.

**Comment by jbride** [comment]
In the lab blueprint, I removed jenkins DC from openbanking-cicd namespace.
