### ISSUE TITLE
user1 needs to be able to impersonate cluster admin

### ISSUE THREAD

**Issue by satyaj** [gpe-mw-training/rhte2019_E2E_API_Lifecycle_Mgmt_labs#12]
In section 4.1 of Set up lab, user1 is expected to have cluster-admin role and impersonate admin in 2 commands using the --as=system:admin flag. This is not set up in the environment.

hence, user1 needs to have the role set up.

**Comment by jbride** [comment]
instructions now have the student switch to root operating system user.
