### ISSUE TITLE
Build pipeline URL to Jenkins log stale URL

### ISSUE THREAD

**Issue by satyaj** [gpe-mw-training/rhte2019_E2E_API_Lifecycle_Mgmt_labs#13]
The Jenkins URL from the build pipeline URL is stale. 

![Selection_194](https://user-images.githubusercontent.com/5753166/62710355-c3e22200-ba14-11e9-8a25-e9c7bbcdeb2e.png)

URL: https://openbanking-jenkins-openbanking-cicd.apps-3cb2.generic.opentlc.com/job/openbanking-cicd/job/openbanking-cicd-openbanking-gateway-pipeline/2/console instead of correct GUID.

**Comment by jbride** [comment]
No longer relevant because we'll use the Jenkins server instantiated from executing a pipeline buildconfig.
