### ISSUE TITLE
Kamel command line tool to be installed in workstation

### ISSUE THREAD

**Issue by satyaj** [gpe-mw-training/rhte2019_E2E_API_Lifecycle_Mgmt_labs#3]
Kamel is a command line tool for working with camel-k deployments to OCP.

The binary is available here:
https://github.com/apache/camel-k/releases

Tested with latest release 0.3.4

The ansible should install this binary as part of the Ravello build, and also add it to the PATH for the user.

**Comment by satyaj** [comment]
Run "kamel install" in the following 3 namespaces to ensure the camel-k operator is installed:

1. openbanking-api-dev
2. openbanking-api-test
3. openbanking-api-prod

This can be manual step for students in the class as a part of set up lab.

**Comment by jbride** [comment]
```
# /usr/local/bin/kamel install --cluster-setup
Camel K cluster setup completed successfully
```

**Comment by satyaj** [comment]
Installed. closed
