### ISSUE TITLE
Set up service account roles for using jenkins cicd

### ISSUE THREAD

**Issue by satyaj** [gpe-mw-training/rhte2019_E2E_API_Lifecycle_Mgmt_labs#4]
Set up the permissions for "jenkins" service account in "openbanking-cicd" to have edit access to "openbanking-api-dev", "openbanking-api-test" and "openbanking-api-prod" namespaces.

Set up role system:image-puller to the default account in  "openbanking-api-test" and  "openbanking-api-prod" to the "openbanking-api-dev" namespace.

**Comment by jbride** [comment]
```
 oc policy add-role-to-user edit system:serviceaccount:openbanking-cicd:jenkins -n openbanking-api-dev
 oc policy add-role-to-user edit system:serviceaccount:openbanking-cicd:jenkins -n openbanking-api-test
 oc policy add-role-to-user edit system:serviceaccount:openbanking-cicd:jenkins -n openbanking-api-prod
 oc policy add-role-to-user system:image-puller system:serviceaccount:openbanking-api-test:default -n openbanking-api-dev
 oc policy add-role-to-user system:image-puller system:serviceaccount:openbanking-api-prod:default -n openbanking-api-dev

```

**Comment by satyaj** [comment]
Working as expected. Closing

**Comment by jbride** [comment]
In order to support jenkins using Nexus, the following is needed:

oc policy add-role-to-user basic-user system:serviceaccount:openbanking-cicd:jenkins -n openbanking-nexus
