### ISSUE TITLE
3scale toolbox binary in workstation to be updated to version 0.12.3

### ISSUE THREAD

**Issue by satyaj** [gpe-mw-training/rhte2019_E2E_API_Lifecycle_Mgmt_labs#6]
The 3scale toolbox used in the container is 0.12.3, whereas the toolbox version is 0.10.0. In order to be consistent, and to provide ability for users to run same commands from CLI , we should upgrade the toolbox version to 0.12.3.

**Comment by jbride** [comment]
rpm -ivh https://github.com/3scale/3scale_toolbox_packaging/releases/download/v0.12.3/3scale-toolbox-0.12.3-1.el7.x86_64.rpm

**Comment by satyaj** [comment]
Updated. Closing issue.
