### ISSUE TITLE
Add wildcard routes for DEV and PROD gateways

### ISSUE THREAD

**Issue by satyaj** [gpe-mw-training/rhte2019_E2E_API_Lifecycle_Mgmt_labs#9]
As wc-router is part of the gateway deployment for DEV and PROD gateway projects, we should have the wildcard router for each env as follows:

<any string>.$TENANT_NAME_DEV.$OCP_WILDCARD_DOMAIN

and 
<any string>.$TENANT_NAME_PROD.$OCP_WILDCARD_DOMAIN

We should then use the wildcard domains in the Jenkins to create the staging and production routes to prevent the manual steps in creating the routes.

**Comment by jbride** [comment]
The following was executed on the latest lab blueprint:

oc set env dc/router ROUTER_ALLOW_WILDCARD_ROUTES=true -n default

**Comment by satyaj** [comment]
I ordered a latest lab environment and still see an issue with wildcard routes.

![Selection_193](https://user-images.githubusercontent.com/5753166/62698259-57f2c000-b9fa-11e9-9123-81d2eeb7d148.png)

**Comment by jbride** [comment]
Refresh script now creates a route for the wc-router with for example the following host:

wc-router.openbanking-prod-gw.apps-a9fd.generic.opentlc.com
